@echo off
cd /d "%~dp0"
echo Initializing Git repository in current directory...
if not exist .git git init
echo Adding remote origin...
git remote add origin https://github.com/codefoxsoft/Java 2>nul
echo Adding files...
git add .
echo Committing files...
git commit -m "Update sorted Java projects"
echo Pulling latest changes from GitHub (Rebase)...
git pull origin main --allow-unrelated-histories --rebase
echo Renaming branch to main...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
pause
