@echo off
cd /d "%~dp0"
echo Initializing Git repository in current directory...
git init
echo Adding remote origin...
git remote add origin https://github.com/codefoxsoft/Java
echo Adding files...
git add .
echo Committing files...
git commit -m "Initial commit of sorted Java projects"
echo Renaming branch to main...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
pause
